version: 2

sources:
 - name: Airbnb
   description: Airbnb dataset (Airbnb is an online accommodation booking platform that allows users to reserve an entire property or a room, for one or more nights, with a local resident or in tourist accommodation.)
   tables:
     - name: listing
       description: list of the accomodations (informs us about the room_type, the host_response_time and the review_scores_value)
     - name: calendar
       description: availiabilities and price of the accomodations from 2022-09-09 to 2023-01-31argumentsarguments

models:
   - name: stg_Airbnb__listing
     description: raw data of list of accomodation list
     columns:
       - name: listing_id
         description: id of the accomodation. Primary key
         tests:
           - unique
           - not_null
       - name: room_type
         description: type of accomodation (Entire home/apt, Private room, Shared room)
         tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt','Private room','Shared room']
       - name: host_response_time
         description: host response time (within an hour, within a few hours, within a day, a few days or more)
         tests:
           - accepted_values:
               arguments:
                 values: ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
       - name: review_scores_value
         description: accommodation rating out of 5

   - name: stg_Airbnb__calendar
     description: raw data of list of accomodation list
     columns:
       - name: listing_id
         description: id of the accomodation
       - name: date_date
         description: date that goes from 2022-09-09 to 2023-01-31
       - name: available
         description: True of False. Indicates if the accomodation was rented on the given date
         tests:
           - accepted_values:
               arguments:
                 values: [true,false]
                 quote: false
       - name: price
         description: price of the accomodation on the given date
         
   - name: int_listing_updated
     description: listing table with a new review_score_category column
     columns:
       - name: listing_id
         description: id of the accomodation. Primary key
         tests:
           - unique
           - not_null
       - name: room_type
         description: type of accomodation (Entire home/apt, Private room, Shared room)
         tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt','Private room','Shared room']
       - name: host_response_time
         description: host response time (within an hour, within a few hours, within a day, a few days or more)
         tests:
           - accepted_values:
               arguments:
                 values: ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
       - name: review_scores_value
         description: accommodation rating out of 5
       - name: review_score_category
         description: '{{ doc("review_score_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Premium', 'High Quality', 'Fair', 'Below Average', 'Low Performing']
   
   - name: int_calendar_updated
     description: new calendar table with the new rented and price category columns 
     columns:
       - name: listing_id
         description: id of the accomodation
       - name: date_date
         description: date that goes from 2022-09-09 to 2023-01-31
       - name: price
         description: price of the accomodation on the given date 
       - name: price_category
         description: '{{ doc("price_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Budget', 'Mid Range', 'Premium', 'Luxury', 'Ultra Luxury']
       - name: rented
         description: Is the accomodation rented at the given date ? 1 for yes and 0 for no
         tests:
           - accepted_values:
               arguments:
                 values: [0,1]
                 quote: false

   - name: int_join_calendar_listing
     description: join of the new tables calendar_updated and listing_updated
     columns:
       - name: listing_id
         description: id of the accomodation. Primary key
         tests:
           - not_null
       - name: date_date
         description: date that goes from 2022-09-09 to 2023-01-31
       - name: room_type
         description: type of accomodation (Entire home/apt, Private room, Shared room)
         tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt','Private room','Shared room']
       - name: host_response_time
         description: host response time (within an hour, within a few hours, within a day, a few days or more)
         tests:
           - accepted_values:
               arguments:
                 values: ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
       - name: price
         description: price of the accomodation on the given date 
       - name: price_category
         description: '{{ doc("price_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Budget', 'Mid Range', 'Premium', 'Luxury', 'Ultra Luxury'] 
       - name: review_scores_value
         description: accommodation rating out of 5
       - name: review_score_category
         description: '{{ doc("review_score_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Premium', 'High Quality', 'Fair', 'Below Average', 'Low Performing']
       - name: rented
         description: Is the accomodation rented at the given date ? 1 for yes and 0 for no
         tests:
           - accepted_values:
               arguments:
                 values: [0,1]
                 quote: false 