version: 2

sources:
 - name: Airbnb
   description: Airbnb dataset (Airbnb is an online accommodation booking platform that allows users to reserve an entire property or a room, for one or more nights, with a local resident or in tourist accommodation.)
   tables:
     - name: listing
       description: list of the accomodations (informs us about the room_type, the host_response_time and the review_scores_value)
     - name: calendar
       description: availiabilities and price of the accomodations from 2022-09-09 to 2023-01-31

models:
   - name: stg_Airbnb__listing
     description: raw data of the accomodation list
     columns:
       - name: listing_id
         description: id of the accomodation. Primary key
         tests:
           - unique
           - not_null
       - name: room_type
         description: type of accomodation (Entire home/apt, Private room, Shared room)
         tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt','Private room','Shared room']
       - name: host_response_time
         description: the average response time displayed in Airbnb to customers (within an hour, within a few hours, within a day, a few days or more)
         tests:
           - accepted_values:
               arguments:
                 values: ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
       - name: review_scores_value
         description: The average review score of each accommodation. Rating out of 5.

   - name: stg_Airbnb__calendar
     description: raw data of the bookings from 2022-09-09 to 2023-01-31. On the 09-09-2022, only 101 accomodations are represented. For all the other dates, there are 500 accomodations. 
     columns:
       - name: listing_id
         description: id of the accomodation
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: available
         description: True of False. Indicates if the accomodation was rented on the given date
         tests:
           - accepted_values:
               arguments:
                 values: [true,false]
                 quote: false
       - name: price
         description: price of the accomodation on the given date
         tests:
           - not_null
           - is_positive        
         
   - name: int_listing_updated
     description: listing table with a new review_score_category column
     columns:
       - name: listing_id
         description: id of the accomodation. Primary key
         tests:
           - unique
           - not_null
       - name: room_type
         description: type of accomodation (Entire home/apt, Private room, Shared room)
         tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt','Private room','Shared room']
       - name: host_response_time
         description: the average response time displayed in Airbnb to customers (within an hour, within a few hours, within a day, a few days or more)
         tests:
           - accepted_values:
               arguments:
                 values: ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
       - name: review_scores_value
         description: The average review score of each accommodation. Rating out of 5.
       - name: review_score_category
         description: '{{ doc("review_score_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Premium', 'High Quality', 'Fair', 'Below Average', 'Low Performing']
   
   - name: int_calendar_updated
     description: new calendar table with new rented and price_category columns 
     columns:
       - name: listing_id
         description: id of the accomodation
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: price
         description: price of the accomodation on the given date 
         tests:
           - not_null
           - is_positive
       - name: price_category
         description: '{{ doc("price_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Budget', 'Mid Range', 'Premium', 'Luxury', 'Ultra Luxury']
       - name: rented
         description: indicates the availability of the rental. 1 for rented and 0 for no rented
         tests:
           - accepted_values:
               arguments:
                 values: [0,1]
                 quote: false

   - name: int_join_calendar_listing
     description: join of the new tables calendar_updated and listing_updated
     columns:
       - name: listing_id
         description: id of the accomodation.
         tests:
           - not_null
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: room_type
         description: type of accomodation (Entire home/apt, Private room, Shared room)
         tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt','Private room','Shared room']
       - name: host_response_time
         description: the average response time displayed in Airbnb to customers (within an hour, within a few hours, within a day, a few days or more)
         tests:
           - accepted_values:
               arguments:
                 values: ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
       - name: price
         description: price of the accomodation on the given date 
         tests:
           - not_null
           - is_positive
       - name: price_category
         description: '{{ doc("price_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Budget', 'Mid Range', 'Premium', 'Luxury', 'Ultra Luxury'] 
       - name: review_scores_value
         description: The average review score of each accommodation. Rating out of 5.
       - name: review_score_category
         description: '{{ doc("review_score_category") }}' 
         tests:
           - accepted_values:
               arguments:
                 values: ['Premium', 'High Quality', 'Fair', 'Below Average', 'Low Performing']
       - name: rented
         description: indicates the availability of the rental. 1 for rented and 0 for no rented
         tests:
           - accepted_values:
               arguments:
                 values: [0,1]
                 quote: false 
  
   - name: occupancy_rate_by_date
     description: ratio of booked accomodations for each date
     columns:
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: occupancy_rate
         description: percentage of occupied accomodations at the given date

   - name: occupancy_rate_by_price_category
     description: ratio of booked accomodations for each price category
     columns:
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: occupancy_rate
         description: percentage of occupied accomodations for each price category
  
   - name: occupancy_rate_by_response_time
     description: ratio of booked accomodations according to the response time
     columns:
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: occupancy_rate
         description: percentage of occupied accomodations according to the response time

   - name: occupancy_rate_by_score review
     description: ratio of booked accomodations for each score review category
     columns:
       - name: date_date
         description: date of the rental or non-rental. Goes from 2022-09-09 to 2023-01-31
       - name: occupancy_rate
         description: percentage of occupied accomodations for each score review category

